### ISSUE TITLE
Label placement

### ISSUE THREAD

**Issue by flaushi** [Nono1971/Doctrine-MetadataGrapher#2]
Hi,
I appreciate this bundle a lot, so first of all thanks for it!
However, there is a small issue if too many associations enter one class, see this picture.

![882641ec copy](https://user-images.githubusercontent.com/15819451/34559344-c3d29daa-f141-11e7-8a0d-d5124d9ec130.png)
Is ist possible to either have one line per association or at least have the arrow caption further towards the middle of the arrow ?
Thanks in advance!
Olli

**Comment by Nono1971** [comment]
Hi,
First, I'm sorry for the delay since you posted this issue ^-^ I didn't see the github notification... :s 

I understand what you mean..., I already got worse than this image :D 
Unfortunately, the display is rendered like this by the yuml.me api... and there is nothing I can do from the MetadataGrapher to make it better... => I only generate the string send to yuml.me,.. all the rendering is done there...
